<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Persistence.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VerticalSlice.Domain\VerticalSlice.Domain.csproj" />
  </ItemGroup>
</Project>